
package com.custom.tyyd.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-06-26T11:48:42.339+08:00
 * Generated source version: 3.1.1
 * 
 */
public final class AuthCheckServicePortType_AuthCheckServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.com", "AuthCheckService");

    private AuthCheckServicePortType_AuthCheckServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AuthCheckService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AuthCheckService ss = new AuthCheckService(wsdlURL, SERVICE_NAME);
        AuthCheckServicePortType port = ss.getAuthCheckServiceHttpPort();  
        
        {
        System.out.println("Invoking checkTokenCode...");
        java.lang.String _checkTokenCode_in0 = "";
        java.lang.String _checkTokenCode__return = port.checkTokenCode(_checkTokenCode_in0);
        System.out.println("checkTokenCode.result=" + _checkTokenCode__return);


        }
        {
        System.out.println("Invoking checkAnswer...");
        java.lang.String _checkAnswer_in0 = "";
        java.lang.String _checkAnswer__return = port.checkAnswer(_checkAnswer_in0);
        System.out.println("checkAnswer.result=" + _checkAnswer__return);


        }
        {
        System.out.println("Invoking sendTokenCode...");
        java.lang.String _sendTokenCode_in0 = "";
        java.lang.String _sendTokenCode__return = port.sendTokenCode(_sendTokenCode_in0);
        System.out.println("sendTokenCode.result=" + _sendTokenCode__return);


        }
        {
        System.out.println("Invoking getAsk...");
        java.lang.String _getAsk_in0 = "";
        java.lang.String _getAsk__return = port.getAsk(_getAsk_in0);
        System.out.println("getAsk.result=" + _getAsk__return);


        }
        {
    		System.out.println("Invoking mobileLogon...11");
    		java.lang.String _mobileLogon_in0 = "<request><uid>fdsafdsaf</uid><password>fdsaf</password>	<imei></imei>	<channelID>01</channelID>	<firmID>huawei</firmID>	<serviceID>8528894278356196767</serviceID>	<shortmsg>01</shortmsg>	<sourceIP>10.208.203.211</sourceIP>	<destinationIP>10.210.240.215</destinationIP>	<destinationPort>443,9443</destinationPort>	<extend>		<businessInfo>kuaixin</businessInfo>	</extend></request> ";
    		java.lang.String _mobileLogon__return = port.mobileLogon(_mobileLogon_in0);
    		System.out.println("mobileLogon.result=" + _mobileLogon__return);
    		


        }
    }
    
    public static String login(String url,String xml)
    {
    	URL wsdlURL = null;
		try {
			wsdlURL = new URL("http://10.204.96.225:9080/AuthHub/services/AuthCheckService?wsdl");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	    	
    	AuthCheckService ss = new AuthCheckService(wsdlURL, SERVICE_NAME);
    	AuthCheckServicePortType port = ss.getAuthCheckServiceHttpPort();  
    	
     return port.mobileLogon(xml);    		
    }
    
    public static void test()
    {
    	URL wsdlURL = null;
		try {
			wsdlURL = new URL("http://10.204.96.225:9080/AuthHub/services/AuthCheckService?wsdl");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	    	
    	AuthCheckService ss = new AuthCheckService(wsdlURL, SERVICE_NAME);
    	AuthCheckServicePortType port = ss.getAuthCheckServiceHttpPort();  
    	
    	{
    		System.out.println("Invoking checkTokenCode...");
    		java.lang.String _checkTokenCode_in0 = "";
    		java.lang.String _checkTokenCode__return = port.checkTokenCode(_checkTokenCode_in0);
    		System.out.println("checkTokenCode.result=" + _checkTokenCode__return);
    		
    		
    	}
    	{
    		System.out.println("Invoking checkAnswer...");
    		java.lang.String _checkAnswer_in0 = "";
    		java.lang.String _checkAnswer__return = port.checkAnswer(_checkAnswer_in0);
    		System.out.println("checkAnswer.result=" + _checkAnswer__return);
    		
    		
    	}
    	{
    		System.out.println("Invoking sendTokenCode...");
    		java.lang.String _sendTokenCode_in0 = "";
    		java.lang.String _sendTokenCode__return = port.sendTokenCode(_sendTokenCode_in0);
    		System.out.println("sendTokenCode.result=" + _sendTokenCode__return);
    		
    		
    	}
    	{
    		System.out.println("Invoking getAsk...");
    		java.lang.String _getAsk_in0 = "";
    		java.lang.String _getAsk__return = port.getAsk(_getAsk_in0);
    		System.out.println("getAsk.result=" + _getAsk__return);
    		
    		
    	}
    	{
    		System.out.println("Invoking mobileLogon...11");
    		java.lang.String _mobileLogon_in0 = "<request><uid>fdsafdsaf</uid><password>fdsaf</password>	<imei></imei>	<channelID>01</channelID>	<firmID>huawei</firmID>	<serviceID>8528894278356196767</serviceID>	<shortmsg>01</shortmsg>	<sourceIP>10.208.203.211</sourceIP>	<destinationIP>10.210.240.215</destinationIP>	<destinationPort>443,9443</destinationPort>	<extend>		<businessInfo>kuaixin</businessInfo>	</extend></request> ";
    		java.lang.String _mobileLogon__return = port.mobileLogon(_mobileLogon_in0);
    		System.out.println("mobileLogon.result=" + _mobileLogon__return);
    		
    		
    	}
    }

}
