package com.custom.tyyd.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-06-26T11:48:42.479+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "AuthCheckService", 
                  wsdlLocation = "http://10.204.96.225:9080/AuthHub/services/AuthCheckService?wsdl",
                  targetNamespace = "http://services.com") 
public class AuthCheckService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.com", "AuthCheckService");
    public final static QName AuthCheckServiceHttpPort = new QName("http://services.com", "AuthCheckServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.204.96.225:9080/AuthHub/services/AuthCheckService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthCheckService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.204.96.225:9080/AuthHub/services/AuthCheckService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthCheckService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthCheckService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthCheckService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AuthCheckService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthCheckService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthCheckService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AuthCheckServicePortType
     */
    @WebEndpoint(name = "AuthCheckServiceHttpPort")
    public AuthCheckServicePortType getAuthCheckServiceHttpPort() {
        return super.getPort(AuthCheckServiceHttpPort, AuthCheckServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthCheckServicePortType
     */
    @WebEndpoint(name = "AuthCheckServiceHttpPort")
    public AuthCheckServicePortType getAuthCheckServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(AuthCheckServiceHttpPort, AuthCheckServicePortType.class, features);
    }

}
