
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.custom.tyyd.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-06-26T11:48:42.430+08:00
 * Generated source version: 3.1.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "AuthCheckService",
                      portName = "AuthCheckServiceHttpPort",
                      targetNamespace = "http://services.com",
                      wsdlLocation = "http://10.204.96.225:9080/AuthHub/services/AuthCheckService?wsdl",
                      endpointInterface = "com.custom.tyyd.client.AuthCheckServicePortType")
                      
public class AuthCheckServiceHttpPortImpl implements AuthCheckServicePortType {

    private static final Logger LOG = Logger.getLogger(AuthCheckServiceHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.custom.tyyd.client.AuthCheckServicePortType#checkTokenCode(java.lang.String  in0 )*
     */
    public java.lang.String checkTokenCode(java.lang.String in0) { 
        LOG.info("Executing operation checkTokenCode");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.custom.tyyd.client.AuthCheckServicePortType#checkAnswer(java.lang.String  in0 )*
     */
    public java.lang.String checkAnswer(java.lang.String in0) { 
        LOG.info("Executing operation checkAnswer");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.custom.tyyd.client.AuthCheckServicePortType#sendTokenCode(java.lang.String  in0 )*
     */
    public java.lang.String sendTokenCode(java.lang.String in0) { 
        LOG.info("Executing operation sendTokenCode");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.custom.tyyd.client.AuthCheckServicePortType#getAsk(java.lang.String  in0 )*
     */
    public java.lang.String getAsk(java.lang.String in0) { 
        LOG.info("Executing operation getAsk");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.custom.tyyd.client.AuthCheckServicePortType#mobileLogon(java.lang.String  in0 )*
     */
    public java.lang.String mobileLogon(java.lang.String in0) { 
        LOG.info("Executing operation mobileLogon");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
